# Generated by Django 3.2.13 on 2022-06-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0047_auto_20200810_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_b2b',
            field=models.BooleanField(default=False),
        ),
    ]
